# -*- coding: utf-8 -*-
"""NetPulse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQqUh7lVpFgIbDDT_lv3TuLCYgKRIss1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import svm
from collections import Counter

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("getanmolgupta01/internet-speed")

path = os.path.join(path, os.listdir(path)[0])
print("Path to dataset files:", path)

df = pd.read_csv(path)
# print(df)

print('Learning DF')
print(df.columns)

print(df.iloc[0:2,:])

sns.histplot(x='Internet_speed', data=df, kde=True)

df

df['Internet_speed'].describe()

df_corr = df.corr()
plt.figure(figsize=(10,10))
sns.heatmap(df_corr, annot=True, fmt=".2f", cmap="Blues")
plt.show()

sns.histplot(x='Weather_conditions', kde=True, data=df)

df['Weather_conditions'] = df['Weather_conditions'].astype(int)

df['Weather_conditions'].unique()

#
print(df[df['Weather_conditions'] == 4]['Internet_speed'].describe())
print(df[df['Weather_conditions'] == 3]['Internet_speed'].describe())
print(df[df['Weather_conditions'] == 2]['Internet_speed'].describe())
print(df[df['Weather_conditions'] == 1]['Internet_speed'].describe())
print(df[df['Weather_conditions'] == 0]['Internet_speed'].describe())

df[df['Weather_conditions'] == 3]['Internet_speed'].describe()

df[df['Weather_conditions'] == 2]['Internet_speed'].describe()

df[df['Weather_conditions'] == 1]['Internet_speed'].describe()

df[df['Weather_conditions'] == 0]['Internet_speed'].describe()

print(df_corr['Internet_speed'].sort_values(ascending=False))

df['Signal_strength'].describe()

df = df.drop(columns=['Connection_type_DSL', 'Connection_type_Cable', 'Connection_type_Fiber'], axis=1)

df = df.drop(columns=['Router_distance', 'Network_congestion', 'ISP_quality'], axis=1)

df = df.drop(columns=['Weather_conditions'], axis=1)

df

df_corr = df.corr()
print(df_corr['Internet_speed'].sort_values(ascending=False))

df['Total_bandwidth'] = df['Download_speed'] + df['Upload_speed']
df['Upload_download_ratio'] = df['Upload_speed'] / df['Download_speed']
df['Network_efficiency'] = df['Download_speed'] / df['Ping_latency']
df['Signal_reliability'] = df['Signal_strength'] / (df['Packet_loss_rate'] + 1)

df

df_corr = df.corr()
plt.figure(figsize=(10,10))
sns.heatmap(df_corr, annot=True, fmt=".2f", cmap="Blues")
plt.show()

df_corr['Internet_speed'].sort_values(ascending=False)

df

df_copy = df.copy()

df.isna().sum()

X = df.drop(columns=['Internet_speed'], axis=1)
Y = df['Internet_speed']

print(Y.describe())

print(df.iloc[100:120, :])

import pandas as pd

bins = [0, 500, 1000, 2000, 3000, float('inf')]
labels = [0, 1, 2, 3, 4]

df['Internet_class'] = pd.cut(df['Internet_speed'], bins=bins, labels=labels)

print(df[['Internet_speed', 'Internet_class']].head())

df

sns.countplot(x='Internet_class', data=df)

df

df = df.drop('Internet_speed', axis=1)
df

X = df.drop(columns=['Internet_class'], axis=1)
Y = df['Internet_class']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

lg = LogisticRegression()
print('Logistictic Regression')
lg.fit(X_train_scaled, Y_train)
X_train_prediction = lg.predict(X_train_scaled)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy score of the training data : ', training_data_accuracy)
X_test_prediction = lg.predict(X_test_scaled)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score of the test data : ', test_data_accuracy)


svm = svm.SVC()
print('Support Vector Machine')
svm.fit(X_train_scaled, Y_train)
X_train_prediction = svm.predict(X_train_scaled)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy score of the training data : ', training_data_accuracy)
X_test_prediction = svm.predict(X_test_scaled)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score of the test data : ', test_data_accuracy)

rf = RandomForestClassifier()
print('Random Forest Classifier')
rf.fit(X_train_scaled, Y_train)
X_train_prediction = rf.predict(X_train_scaled)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy score of the training data : ', training_data_accuracy)
X_test_prediction = rf.predict(X_test_scaled)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score of the test data : ', test_data_accuracy)

df.columns

import numpy as np

print('Enter ping latency : ')
ping_latency = float(input())

print('Enter download speed : ')
download_speed = float(input())

print('Enter upload speed : ')
upload_speed = float(input())

print('Enter signal strength : ')
signal_strength = float(input())

print('Enter packet loss rate : ')
packet_loss_rate = float(input())

# Derived features
bandwidth = download_speed + upload_speed
upload_download_ratio = upload_speed / download_speed
network_efficiency = download_speed / ping_latency
signal_reliability = signal_strength / (packet_loss_rate + 1)

# Create input array (same order as training data)
input_data = np.array([[
    ping_latency,
    download_speed,
    upload_speed,
    packet_loss_rate,
    signal_strength,
    bandwidth,
    upload_download_ratio,
    network_efficiency,
    signal_reliability
]])

# Scale the data
input_scaled = sc.transform(input_data)

# Predictions
lg_pred = lg.predict(input_scaled)
svm_pred = svm.predict(input_scaled)
rf_pred = rf.predict(input_scaled)
print("Logistic Regression Prediction:", lg_pred[0])
print("SVM Prediction:", svm_pred[0])
print("Random Forest Prediction:", rf_pred[0])



predictions = [lg_pred[0], svm_pred[0], rf_pred[0]]
final_prediction = Counter(predictions).most_common(1)[0][0]
print("Final Prediction : " , final_prediction)