# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106w3XJPW3rQMUvmrMY9y5uPJgv_Cz2h5
"""



"""# **Banking Campaign Analysis**

## **Data Preprocessing**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
stop_words = set(stopwords.words('english'))

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("prakharrathi25/banking-dataset-marketing-targets")
path = os.path.join(path, os.listdir(path)[0])

print("Path to dataset files:", path)

os.listdir(os.path.dirname(path))

#Loading the dataset

df = pd.read_csv(path, sep=";")
df

"""## **Explorative Data Analysis**"""

#Analysing the dataset

# 1. Columns of datset
print(df.columns)
# 2. Shape of dataset
print(df.shape)

df.isna().sum()

cols = ['job', 'marital','education','default','housing','loan',
        'contact','poutcome','y']

label_features = {col: df[col].unique() for col in cols}

for i in label_features:
  print(i)
  for j, k in enumerate(label_features[i]):
    df[i] = df[i].replace(k, j)
    print(str(k) + ":" + str(j))
  print("\n")

df['month'] = df['month'].replace({'jan':1, 'feb':2, 'mar':3, 'apr':4, 'may':5, 'jun':6, 'jul':7, 'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec':12})

df

print(df.describe())

"""## **Data Visualisation**"""

df

df.hist(figsize=(20,20))
plt.show()

# Count of jobs and the count of persons who subscribed to a deposit plan

for i,j in enumerate(label_features['job']):
  print(str(i) + " : " + str(j))

print('\n')
sns.countplot(x='job', hue='y', data=df)

y_counts = df['y'].value_counts()
plt.pie(y_counts, labels=y_counts.index, autopct='%1.1f%%')
plt.title('Distribution of y')
plt.show()

sns.histplot(data=df, x='age', kde=True, bins=23, hue='y')  # histogram + KDE
plt.show()

# Fisher score is a scoring method used to rank columns to determine which feature can seperate the classes efficiently
# Larger the fisher score, the good the feature is to seperate the classes

#Fisher score = (uA - uB)**2 / (varA + varB)

def fisher_score_binary_class(ds, index):
  A = ds[ds.iloc[:,-1] == 0].iloc[:,index]
  B = ds[ds.iloc[:,-1] == 1].iloc[:,index]
  uA = np.mean(A)
  uB = np.mean(B)
  varA = np.var(A, ddof=1)
  varB = np.var(B, ddof =1)
  fisher_score = (uA - uB)**2 / (varA + varB)
  return fisher_score

bank_fisher_score = []
for i in range(0, len(df.columns) - 1):
  bank_fisher_score.append((i, fisher_score_binary_class(df, i)))

bank_fisher_score.sort(key=lambda x: x[1], reverse=True)
for i,j in bank_fisher_score:
    print(df.columns[i] + " : " + str(j))

sns.scatterplot(x='duration', y='balance', hue='y', data=df)

corr_matrix = df.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix,
            annot=True,      # show correlation values
            fmt=".2f",       # 2 decimal places
            cmap="Blues", # color map
            cbar=True)
plt.title("Correlation Heatmap")
plt.show()

sns.scatterplot(x='pdays', y='poutcome', hue='y', data=df)

"""## **Data Standardisation**"""

df_0 = df[df['y'] == 0]
df_1 = df[df['y'] == 1]

print(X.shape)
print(df[df['y'] == 0].shape)
print(df[df['y'] == 1].shape)

df_0_sampled = df_0.sample(n=5289, random_state=42)
df_1_sampled = df_1
df_combined = pd.concat([df_0_sampled, df_1_sampled])

X = df_combined.drop(columns=['y'], axis=1)
Y = df_combined['y']

X_train = X
Y_train = Y

path = os.path.dirname(path)

path = os.path.join(path, os.listdir(path)[1])
print(path)

test_df = pd.read_csv(path, sep=';')
test_df

test_df = test_df.replace({
    "job": {
        "management": 0,
        "technician": 1,
        "entrepreneur": 2,
        "blue-collar": 3,
        "unknown": 4,
        "retired": 5,
        "admin.": 6,
        "services": 7,
        "self-employed": 8,
        "unemployed": 9,
        "housemaid": 10,
        "student": 11
    },
    "marital": {
        "married": 0,
        "single": 1,
        "divorced": 2
    },
    "education": {
        "tertiary": 0,
        "secondary": 1,
        "unknown": 2,
        "primary": 3
    },
    "default": {
        "no": 0,
        "yes": 1
    },
    "housing": {
        "yes": 0,
        "no": 1
    },
    "loan": {
        "no": 0,
        "yes": 1
    },
    "contact": {
        "unknown": 0,
        "cellular": 1,
        "telephone": 2
    },
    "poutcome": {
        "unknown": 0,
        "failure": 1,
        "other": 2,
        "success": 3
    },
    "y": {
        "no": 0,
        "yes": 1
    }
})

test_df

test_df['month'] = test_df['month'].replace({'jan':1, 'feb':2, 'mar':3, 'apr':4, 'may':5, 'jun':6, 'jul':7, 'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec':12})

test_df

X_test = test_df.drop(columns=['y'], axis=1)
Y_test = test_df['y']

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""## **Model Evaluation**

**Logistic Regression**
"""

lg_model = LogisticRegression(max_iter=1000)
lg_model.fit(X_train, Y_train)
X_train_pred = lg_model.predict(X_train)
X_test_pred = lg_model.predict(X_test)
print('Training Accuracy : ', accuracy_score(X_train_pred, Y_train))
print('Testing Accuracy : ', accuracy_score(X_test_pred, Y_test))

"""**Random Forest Classifier**"""

rf_model = RandomForestClassifier()
rf_model.fit(X_train, Y_train)
X_train_pred = rf_model.predict(X_train)
X_test_pred = rf_model.predict(X_test)
print('Training Accuracy : ', accuracy_score(X_train_pred, Y_train))
print('Testing Accuracy : ', accuracy_score(X_test_pred, Y_test))

"""**Support Vector Classifier**"""

from sklearn.svm import SVC
kernel = ['linear', 'rbf', 'poly', 'sigmoid']
for k in kernel:
  svc_model = SVC(kernel = k)
  svc_model.fit(X_train, Y_train)
  X_train_pred = svc_model.predict(X_train)
  X_test_pred = svc_model.predict(X_test)
  print('Training Accuracy : ', accuracy_score(X_train_pred, Y_train))
  print('Testing Accuracy : ', accuracy_score(X_test_pred, Y_test))

"""**K Nearest Neighbour**"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)

X_train_pred = knn.predict(X_train)
X_test_pred = knn.predict(X_test)

print('k : ', 5)
print("Training Accuracy :", accuracy_score(Y_train, X_train_pred))
print("Testing Accuracy  :", accuracy_score(Y_test, X_test_pred))

knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, Y_train)

X_train_pred = knn.predict(X_train)
X_test_pred = knn.predict(X_test)

print('k : ', 4)
print("Training Accuracy :", accuracy_score(Y_train, X_train_pred))
print("Testing Accuracy  :", accuracy_score(Y_test, X_test_pred))

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, Y_train)

X_train_pred = knn.predict(X_train)
X_test_pred = knn.predict(X_test)

print('k : ', 3)
print("Training Accuracy :", accuracy_score(Y_train, X_train_pred))
print("Testing Accuracy  :", accuracy_score(Y_test, X_test_pred))

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, Y_train)

X_train_pred = knn.predict(X_train)
X_test_pred = knn.predict(X_test)

print('k : ', 6)
print("Training Accuracy :", accuracy_score(Y_train, X_train_pred))
print("Testing Accuracy  :", accuracy_score(Y_test, X_test_pred))

