# -*- coding: utf-8 -*-
"""Malicious URL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106w3XJPW3rQMUvmrMY9y5uPJgv_Cz2h5
"""



"""# **Malicious URL Detection**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
stop_words = set(stopwords.words('english'))

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("sid321axn/malicious-urls-dataset")

path = os.path.join(path, os.listdir(path)[0])
print(path)

df = pd.read_csv(path)
df

df['type'].value_counts()

df_2_classified = df.replace({'type':{'benign':0, 'defacement':1, 'phishing':1, 'malware':1}}, inplace=False)

df_2_classified['type'].value_counts()

#Imbalancement Management

df_2_classified_benign = df_2_classified[df_2_classified['type'] == 0]
df_2_classified_malware = df_2_classified[df_2_classified['type'] == 1]

print(df_2_classified_benign.shape)
print(df_2_classified_malware.shape)

df_2_classified_benign = df_2_classified_benign.sample(n=223088, random_state=2)
print(df_2_classified_benign.shape)
print(df_2_classified_malware.shape)

df_2_classified= pd.concat([df_2_classified_benign, df_2_classified_malware])
df_2_classified

url_vec = TfidfVectorizer()

X = df_2_classified['url']
Y = df_2_classified['type']
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, stratify=Y, random_state=2)

X_train_vec = url_vec.fit_transform(X_train)
X_test_vec = url_vec.transform(X_test)

model_lg = LogisticRegression()
model_lg.fit(X_train_vec, Y_train)

X_train_vec_pred = model_lg.predict(X_train_vec)
X_test_vec_pred = model_lg.predict(X_test_vec)
print('Training Accuracy : ', accuracy_score(X_train_vec_pred, Y_train))
print('Testing Accuracy : ', accuracy_score(X_test_vec_pred, Y_test))

