# -*- coding: utf-8 -*-
"""Fake New Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106w3XJPW3rQMUvmrMY9y5uPJgv_Cz2h5
"""



"""# **Fake News Classification**"""

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
stop_words = set(stopwords.words('english'))

import kagglehub

# Download latest version
path = kagglehub.dataset_download("hassanamin/textdb3")


path = os.path.join(path, os.listdir(path)[0])
print(path)

df = pd.read_csv(path)
df

# Understanding all the columns of dataset

print('Shape : ', df.shape)
print('Columns : ', df.columns)

# Dropping the Unnamed: 0 column
df = df.drop(columns=['Unnamed: 0'], axis=1)

# Analysing Missing values
df.isna().sum()

# Replacing target variables
df['label'] = df['label'].replace({'FAKE' : 0, 'REAL': 1})
df

port_stem = PorterStemmer()
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if word not in stop_words]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

df['text'] = df['text'].apply(stemming)

X = df[['title', 'text']]
Y = df['label']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

title_vec = TfidfVectorizer(max_features=5000)
text_vec = TfidfVectorizer(max_features=20000)

title_train = title_vec.fit_transform(X_train['title'])
text_train = text_vec.fit_transform(X_train['text'])

title_test = title_vec.transform(X_test['title'])
text_test = text_vec.transform(X_test['text'])

from scipy.sparse import hstack
X_train_vec = hstack([title_train, text_train])
X_test_vec = hstack([title_test, text_test])



fake_news_model_lg = LogisticRegression()
fake_news_model_lg.fit(X_train_vec, Y_train)

X_train_pred = fake_news_model_lg.predict(X_train_vec)
X_test_pred = fake_news_model_lg.predict(X_test_vec)
print("Training Accuracy: ", accuracy_score(X_train_pred, Y_train))
print("Testing Accuracy: ", accuracy_score(X_test_pred, Y_test))